### ISSUE TITLE
expo doctor issue

### ISSUE THREAD

**Issue by ahmad11111111111** [umnil/bci-app#11]
having issues running expo doctor on laptop. ran deleted the package.lock
```➜  bci-app git:(7-handle-all-unhandled-promise-rejections) ✗ npx expo-doctor
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

One or more checks failed, indicating possible issues with the project.
➜  bci-app git:(7-handle-all-unhandled-promise-rejections) ✗ 
```

**Comment by kevincar** [comment]
The error is:

```
This project has native project folders
```

This means you have folders like `iOS` and `Android` somewhere in your project. You need to remove those.

**Comment by ahmad11111111111** [comment]
Gottit

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin Davis ***@***.***>
Sent: Tuesday, December 19, 2023 10:05:24 PM
To: umnil/bci-app ***@***.***>
Cc: Al-Salem, Ahmad Tarik ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [umnil/bci-app] expo doctor issue (Issue #11)

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.

The error is:

This project has native project folders


This means you have folders like iOS and Android somewhere in your project. You need to remove those.

**Comment by kevincar** [comment]
Updated the merged branches. This is resolved your recent merge request. Re-open if you're still having the issue after checking out the latest updates
